mysite/urls.py
from django.contrib import admin
from django.urls import include, path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("whistleblower_site.urls")),
    path("", include("allauth.urls")),
    path("", RedirectView.as_view(url='/login/'))
]

whistleblower_site/urls.py
from django.urls import path
from . import views

app_name = 'orgreport'
urlpatterns = [
    # ex: /orgreport/login
    path("login/", views.login, name="login"),
    # ex: /orgreport/home
    path("home/", views.home, name="home"),
    path('find_resources/', views.find_resources, name='find_resources'),
    path('search_reports/', views.search_reports, name='search_reports'),
    path('report/<int:report_id>/', views.report_detail, name='report_detail'),
    path('home/uploaded_files/', views.s3_folder_view, name='s3_folder_view'),
    path("logout/", views.logout_view, name="logout"),
    path("download_file/<path:file_key>/", views.download_file, name="download_file"),
    path("report/", views.report, name="report"),
    path("profile/", views.profile, name="profile"),
    path('user_report/<int:report_id>/', views.report_detail_user, name='report_detail_user'),
    path('delete_report/<int:report_id>/', views.delete_report, name='delete_report'),
]

whistleblower_site/models.py
import os
from django.db import models

# User class to store user information
class User(models.Model):
    first_name = models.CharField(max_length=100, default='John')
    last_name = models.CharField(max_length=100, default='Doe')
    email = models.EmailField(default='placeholder@example.com')

    def __str__(self):
        return self.email

class Report(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    organization = models.CharField(max_length=100)
    date = models.DateTimeField()
    location = models.CharField(max_length=100)
    description = models.TextField()
    publish = models.BooleanField()
    anonymous_account = models.BooleanField(null=True, blank=True)
    STATUS_CHOICES = [
        ('new', 'New'),
        ('in_progress', 'In Progress'),
        ('resolved', 'Resolved'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')
    admin_notes = models.TextField(blank=True)

    def __str__(self):
        return self.date.strftime('%Y-%m-%d %H:%M:%S')
    
class ReportFile(models.Model):
    report = models.ForeignKey(Report, related_name='report_files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='org-report-uploaded-files/')

    def filename(self):
        return os.path.basename(self.file.name)

    def file_url(self):
        if self.file:
            return self.file.url
        return None

whistleblower_site/forms.py
from django import forms
from .models import Report

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['first_name', 'last_name', 'email', 'organization', 'date', 'location', 'description', 'publish', 'anonymous_account']

whistleblower_site/views.py
from django.contrib.auth import logout
import boto3
from django.shortcuts import get_object_or_404, redirect, render
from django.conf import settings
import mimetypes
from django.core.exceptions import ValidationError
import os

from django.urls import reverse
from .models import Report, User, ReportFile
from .forms import ReportForm

from django.http import HttpResponse

def logout_view(request):
    logout(request)
    return render(request, "whistleblower_site/login.html")

def login(request):
    # Log out any user who is currently logged in
    if request.user.is_authenticated:
        logout(request)
    return render(request, "whistleblower_site/login.html")

def home(request):
    user = request.user
    user_groups = user.groups.values_list('name', flat=True)
    #If the user logged in
    if user.is_authenticated:
        users = User.objects.all()
        #Search for the user in the database
        for ind_user in users:
            #If the user is in the database, return the home page with the user's information
            if ind_user.email == user.email:
                return render(request, "whistleblower_site/home.html", {'user': user, 'user_groups': user_groups})
        #If the user is not in the database, add them with their first name, last name, and email
        new_user = User(first_name=user.first_name, last_name=user.last_name, email=user.email)
        new_user.save()

    return render(request, "whistleblower_site/home.html", {'user': user, 'user_groups': user_groups})

def download_file(request, file_key):
    s3 = boto3.client(
        's3',
        aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
        aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
        region_name=settings.AWS_S3_REGION_NAME
    )

    bucket_name = 'org-report-storage-bucket'
    file_path = 'org-report-uploaded-files/' + file_key

    try:
        # Retrieve the file object from S3
        response = s3.get_object(Bucket=bucket_name, Key=file_path)
        file_content = response['Body'].read()

        # Determine the file's MIME type based on its extension
        content_type, _ = mimetypes.guess_type(file_key)
        if not content_type:
            content_type = 'application/octet-stream'

        # Serve the file content as the HTTP response with appropriate content type
        response = HttpResponse(file_content, content_type=content_type)
        response['Content-Disposition'] = f'attachment; filename="{file_key}"'
        return response
    except Exception as e:
        # Return a 404 error if the file does not exist or there's an error retrieving it
        return HttpResponse(status=404)

def s3_folder_view(request):
    user = request.user
    user_groups = user.groups.values_list('name', flat=True)
    organization_query = request.GET.get('org')
    after_query = request.GET.get('after')
    before_query = request.GET.get('before')
    reset_query = request.GET.get('reset')
    status_query = request.GET.get('status')
    reports = Report.objects.all()

    if reset_query:
        organization_query=None
        after_query=None
        before_query=None
        status_query=None
        reports = Report.objects.all()
    else:
        if organization_query:
            reports = reports.filter(organization__icontains=organization_query)
        if after_query:
            reports = reports.filter(date__gte=after_query)
        if before_query:
            reports = reports.filter(date__lte=before_query)
        if status_query:
            if status_query == 'In Progress':
                status_query = 'in_progress'
            elif status_query == 'All':
                status_query = ''
            reports = reports.filter(status__icontains=status_query)

    report_data = [{
    'report': report,
    'status': report.status,
    'admin_notes': report.admin_notes,
    } for report in reports]

    return render(request, 'whistleblower_site/s3_folder_view.html', {
        'report_data': report_data, 
        'user': user, 
        'user_groups': user_groups,
        'organization_query':organization_query, 
        'after_query':after_query, 
        'before_query':before_query, 
        'status_query':status_query,
        'reset_query':reset_query
    })



def report(request):
    user = request.user
    user_groups = user.groups.values_list('name', flat=True)
    if request.method == 'POST':
        return upload_file(request)
    return render(request, "whistleblower_site/report.html", {'user': user, 'user_groups': user_groups})

ALLOWED_EXTENSIONS = ['.txt', '.pdf', '.jpg']

def validate_file_extension(file):
    # Extract the file extension
    _, extension = os.path.splitext(file.name)
    if extension.lower() not in ALLOWED_EXTENSIONS:
        raise ValidationError(f'Unsupported file type. Only {", ".join(ALLOWED_EXTENSIONS)} files are allowed.')

def upload_file(request):
    user_groups = request.user.groups.values_list('name', flat=True)
    form = ReportForm(request.POST, request.FILES)
    if form.is_valid():
        report = form.save(commit=False)
        if request.user.is_authenticated:
            try:
                user = User.objects.get(email=request.user.email, first_name=request.user.first_name, last_name=request.user.last_name)
                report.user = user
                report.anonymous_account = False
            except User.DoesNotExist:
                pass
        else:
            report.anonymous_account = True
        report.save()
    else: 
        return render(request, 'whistleblower_site/report.html', {'user': request.user, 'user_groups': user_groups})
    
    if 'file' in request.FILES:
        files = request.FILES.getlist('file')
        for file in files:
            try:
                validate_file_extension(file)
                ReportFile.objects.create(report=report, file=file)
            except ValidationError as e:
                return render(request, 'whistleblower_site/report.html', {'user': request.user, 'user_groups': user_groups, 'error': e.message}) 
        return render(request, 'whistleblower_site/report.html', {'user': request.user, 'user_groups': user_groups, 'submitted': True})
    else:
        return render(request, 'whistleblower_site/report.html', {'user': request.user, 'user_groups': user_groups, 'submitted': True})

def find_resources(request):
    user = request.user
    user_groups = user.groups.values_list('name', flat=True)
    return render(request, "whistleblower_site/resources.html", {'user': user, 'user_groups': user_groups})

def search_reports(request):
    user = request.user
    user_groups = user.groups.values_list('name', flat=True)
    organization_query = request.GET.get('org')
    after_query = request.GET.get('after')
    before_query = request.GET.get('before')
    reset_query = request.GET.get('reset')

    reports = Report.objects.filter(publish=True)
    if reset_query:
        organization_query=None
        after_query=None
        before_query=None
        reports = Report.objects.filter(publish=True)
    else:
        if organization_query:
            reports = reports.filter(organization__icontains=organization_query)
        if after_query:
            reports = reports.filter(date__gte=after_query)
        if before_query:
            reports = reports.filter(date__lte=before_query)
    return render(request, "whistleblower_site/search_reports.html", {'reports': reports, 'user': user, 'user_groups': user_groups, 'organization_query':organization_query, 'after_query':after_query, 'before_query':before_query, 'reset_query':reset_query})


def report_detail(request, report_id):
    user = request.user
    user_groups = user.groups.values_list('name', flat=True)
    report = get_object_or_404(Report, pk=report_id)
    if 'admin' in request.user.groups.values_list('name', flat=True) and report.status == 'new':
        report.status = 'in_progress'
        report.save()

    context = {
        'report': report,
        'user': user,
        'user_groups': user_groups
    }

    if request.method == 'POST':
        new_status = request.POST.get('status', report.status)
        valid_statuses = ['in_progress', 'resolved']
        if new_status in valid_statuses:
            report.status = new_status
        report.admin_notes = request.POST.get('admin_notes', report.admin_notes)
        report.save()
        context['report'] = report
        return render(request, 'whistleblower_site/report_detail.html', context)

    return render(request, 'whistleblower_site/report_detail.html', context)


def profile(request):
    user = request.user
    user_groups = user.groups.values_list('name', flat=True)
    reports = Report.objects.filter(user__email=user.email)

    report_data = [{
        'report': report,
        'status': report.status,
        'admin_notes': report.admin_notes,
    } for report in reports]

    return render(request, 'whistleblower_site/profile.html', {
        'report_data': report_data,
        'user': user,
        'user_groups': user_groups
    })


def report_detail_user(request, report_id):
    user = request.user
    user_groups = user.groups.values_list('name', flat=True)
    report = get_object_or_404(Report, pk=report_id)

    if 'admin' in request.user.groups.values_list('name', flat=True) and report.status == 'new':
        report.status = 'in_progress'
        report.save()

    context = {
        'report': report,
        'user': user,
        'user_groups': user_groups
    }

    if request.method == 'POST':
        new_status = request.POST.get('status', report.status)
        valid_statuses = ['in_progress', 'resolved']
        if new_status in valid_statuses:
            report.status = new_status
        report.admin_notes = request.POST.get('admin_notes', report.admin_notes)
        report.save()
        context['report'] = report
        return render(request, 'whistleblower_site/report_detail_user.html', context)

whistleblower_site/templates/whistleblower_site/base.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="../../static/whistleblower_site/base.css">
    <link rel="stylesheet" type="text/css" href="../static/whistleblower_site/base.css">
    <title>OrgReport</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light navvy">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'orgreport:home' %}">
            <button class="btn butt">
                Home
            </button>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupported" aria-controls="navbarSupported" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupported">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if 'admin' not in user_groups %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'orgreport:report' %}">
                            <button class="btn butt">
                                Submit a Report
                            </button>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'orgreport:find_resources' %}">
                            <button class="btn butt">
                                Find Resources
                            </button>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'orgreport:search_reports' %}">
                            <button class="btn butt">
                                Report Forum
                            </button>
                        </a>
                    </li>
                {% elif 'admin' in user_groups%}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'orgreport:s3_folder_view' %}">
                            <button class="btn butt">
                                View Submitted Reports
                            </button>
                        </a>
                    </li>
                {% endif %}

            </ul>
            <ul class="navbar-nav">
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'orgreport:login' %}">
                            <button class="btn butt">
                                Login
                            </button>
                        </a>
                    </li>
                {% else %}
                    {% if user.is_superuser%}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">
                                <button class="btn butt">
                                    Admin Login
                                </button>
                            </a>
                        </li>
                    {% endif %}
                    {% if 'admin' not in user_groups %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'orgreport:profile' %}">
                            <button class="btn butt">
                                Profile
                            </button>
                        </a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'orgreport:logout' %}">
                            <button class="btn butt">
                                Logout
                            </button>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container mt-4 content-container">
    {% block content %}
    {% endblock %}
</div>

<footer class="footy py-2 fixed-bottom">
    <div class="container text-light text-center">
        <p class="mb-3">OrgReport</p>
        <small>This system is a class project, is not monitored, and thus no real information should be submitted.</small>
    </div>
</footer>

{% bootstrap_javascript %}
</body>
</html>

whistleblower_site/templates/whistleblower_site/home.html
{% extends 'whistleblower_site/base.html' %}

{% block content %}
<link rel="stylesheet" type="text/css" href="../static/whistleblower_site/home.css">

<div class="main-container">
    <div class="welcome-container">
        {% if user.is_authenticated %}
            <strong>Welcome, {{ user.first_name }} {{ user.last_name }}!</strong>
            <strong>Email: {{ user.email }}</strong>
            {% if 'admin' in user_groups %}
                <p>You are an admin.</p>
                <a href="{% url 'orgreport:s3_folder_view' %}" class="btn btn-info custom-btn">
                    <img src="/static/whistleblower_site/images/view_reports.jpg">
                    <strong>View Submitted Reports</strong>
                </a>
            {% endif %}
        {% else %}
            <strong>Welcome, Anonymous.</strong>
        {% endif %}
    </div>
    <div class="directs-container">
        {% if 'admin' not in user_groups %}
            <a href="{% url 'orgreport:report' %}" class="btn btn-info custom-btn">
                <img src="/static/whistleblower_site/images/submit_a_report.png">
                <strong>Submit a Report</strong>
            </a>
            <a href="{% url 'orgreport:find_resources' %}" class="btn btn-success custom-btn">
                <img src="/static/whistleblower_site/images/find_resources.png">
                <strong>Find Resources</strong>
            </a>
            <a href="{% url 'orgreport:search_reports' %}" class="btn btn-warning custom-btn">
                <img src="/static/whistleblower_site/images/search_image.png">    
                <strong>Report Forum</strong>
            </a>
        {% endif %}
    </div>
</div>
{% endblock %}

whistleblower_site/templates/whistleblower_site/profile.html
{% extends 'whistleblower_site/base.html' %}

{% block title %}Profile Page{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="../static/whistleblower_site/profile.css">

<div class="container mt-4">
    <h1 class="text">My Submitted Reports</h1>

    {% if user.is_authenticated %}
    {% if report_data %}
    <div class="mt-3 mb-3">
        <label for="status-filter">Filter by Status:</label>
        <select id="status-filter" class="form-select input">
            <option value="all">All</option>
            <option value="new">New</option>
            <option value="in_progress">In Progress</option>
            <option value="resolved">Resolved</option>
        </select>
    </div>
    <ul class="list-group report_list">
        {% for data in report_data %}
        <li class="list-group-item report_list report-{{ data.report.status }}">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <h2><a href="{% url 'orgreport:report_detail_user' data.report.id %}" class="link">
                    {{ data.report.description|slice:":40" }}{% if data.report.description|length > 40 %}...{% endif %}
                    </a>
                    </h2>
                    <strong>Date:</strong> {{ data.report.date }}<br>
                    <strong>Organization:</strong> {{ data.report.organization }}<br>
                    <strong>Status:</strong>
                    {% if data.report.status == 'in_progress' %}
                    In Progress
                    {% elif data.report.status == 'resolved' %}
                    Resolved
                    {% else %}
                    New
                    {% endif %}
                </div>
                <div>
                    <a href="{% url 'orgreport:delete_report' data.report.id %}" class="btn butt2">Delete Report</a>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No reports found.</p>
    {% endif %}
    {% else %}
    <div class="alert alert-danger" role="alert">
        You do not have permission to view this content.
    </div>
    {% endif %}
    <a href="{% url 'orgreport:home' %}" class="btn mt-3 butt">Back to Home</a>
</div>

<script>
    // JavaScript to handle filtering
    document.getElementById('status-filter').addEventListener('change', function () {
        var selectedStatus = this.value;
        var reportItems = document.querySelectorAll('.report_list li');

        reportItems.forEach(function (item) {
            if (selectedStatus === 'all' || item.classList.contains('report-' + selectedStatus)) {
                item.style.display = 'block';
            } else {
                item.style.display = 'none';
            }
        });
    });
</script>

{% endblock %}

whistleblower_site/templates/whistleblower_site/report_detail.html
{% extends 'whistleblower_site/base.html' %}

{% block content %}
<link rel="stylesheet" type="text/css" href="../../static/whistleblower_site/report.css">
{% if 'admin' in user_groups %}
    <div class="report-detail">
        <h1>Report Details</h1>
        <div>
            {% if report.anonymous_account %}
                <strong>The report was submitted anonymously</strong>
            {% else %}
                <strong>
                    Full Name:
                </strong>
                {{ report.first_name }} {{ report.last_name }}
                <strong> | Email:</strong> 
                {{ report.email }}
            {% endif %}
        </div>
        <div>
            <strong>Organization Title:</strong> {{ report.organization }}
        </div>
        <div>
            <strong>Date Of Event:</strong> {{ report.date|date:"D, d M Y H:i" }}
        </div>
        <div>
            <strong>Location:</strong> {{ report.location }}
        </div>
        <div>
            <strong>Description of Event:</strong> {{ report.description }}
        </div>
        <div>
            <strong>
                Status: 
            </strong>
            {% if report.status == 'in_progress' %}
                In Progress
            {% elif report.status == 'resolved' %}
                Resolved
            {% else %}
                New
            {% endif %} 
        </div>
        <div>
            <strong>Admin Notes:</strong> {% if report.admin_notes %}{{ report.admin_notes }}{% else %}N/A{% endif %}
        </div>
        {% if report.report_files.all %}
            <div>
                <strong>File(s):</strong>
            {% for file in report.report_files.all %}
                <a href="{% url 'orgreport:download_file' file.filename %}" class="link">{{ file.filename }}</a>
            {% endfor %}
            </div>
        {% else %}
            <div>
                <strong>File:</strong> N/A
            </div>
        {% endif %}
    </div>
    <div class="update-report">
        <form method="post" class="update-form mt-3">
            {% csrf_token %}
            <div class="form-group">
                <label for="status">Status:</label>
                <select id="status" name="status" class="form-control form-field">
                    <option value="in_progress" {% if report.status == 'in_progress' %}selected{% endif %}>In Progress</option>
                    <option value="resolved" {% if report.status == 'resolved' %}selected{% endif %}>Resolved</option>
                </select>
            </div>
            <div class="form-group">
                <label for="admin_notes">Admin Notes:</label>
                <textarea id="admin_notes" name="admin_notes" class="form-control form-field" rows="4">{{ report.admin_notes }}</textarea>
            </div>
            <button type="submit" class="btn butt2 mt-3">
                Update Report
            </button>
            <a href="{% url 'orgreport:s3_folder_view' %}" class="btn butt2 mt-3">
                    Return to Reports
            </a>
        </form>
    </div>
{% else %}
    <div class="alert alert-danger" role="alert">
        You do not have permission to view this content.
    </div>
{% endif %}
{% endblock %}

whistleblower_site/templates/whistleblower_site/report_detail_user.html
{% extends 'whistleblower_site/base.html' %}

{% block content %}
<link rel="stylesheet" type="text/css" href="../../static/whistleblower_site/report_user.css">

<h1>Report Details</h1>
    <div class="report-detail">
        <div>
            {% if report.anonymous_account %}
                <strong>The report was submitted anonymously</strong>
            {% else %}
                <strong>
                    Full Name:
                </strong>
                {{ report.first_name }} {{ report.last_name }}
                <strong> | Email:</strong>
                {{ report.email }}
            {% endif %}
        </div>
        <div>
            <strong>Organization Title:</strong> {{ report.organization }}
        </div>
        <div>
            <strong>Date Of Event:</strong> {{ report.date|date:"D, d M Y H:i" }}
        </div>
        <div>
            <strong>Location:</strong> {{ report.location }}
        </div>
        <div>
            <strong>Description of Event:</strong> {{ report.description }}
        </div>
        <div>
            <strong>
                Status:
            </strong>
            {% if report.status == 'in_progress' %}
                In Progress
            {% elif report.status == 'resolved' %}
                Resolved
            {% else %}
                New
            {% endif %}
        </div>
        <div>
            <strong>Admin Notes:</strong> {% if report.admin_notes %}{{ report.admin_notes }}{% else %}N/A{% endif %}
        </div>
        {% if report.report_files.all %}
            <div>
                <strong>File(s):</strong>
            {% for file in report.report_files.all %}
                <a href="{% url 'orgreport:download_file' file.filename %}" class="link">{{ file.filename }}</a>
            {% endfor %}
            </div>
        {% else %}
            <div>
                <strong>File:</strong> N/A
            </div>
        {% endif %}
    </div>
    <a href="{% url 'orgreport:profile' %}" class="btn mt-3 butt">Back to Profile</a>
{% endblock %}

whistleblower_site/templates/whistleblower_site/s3_folder_view.html
 {% extends 'whistleblower_site/base.html' %}

 {% block content %}
 <link rel="stylesheet" type="text/css" href="../../static/whistleblower_site/s3_folder_view.css">
 <div class="container mt-4">
     <h1>Submitted Reports</h1>
     <div class="container mt-3" style="padding: 0;">
        <form method="GET" action="{% url 'orgreport:s3_folder_view' %}">
            {% csrf_token %}
            <label for="org">Organization: </label>
            <input type="text" class="input form-field" id="org" name="org" value="{% if organization_query %}{{ organization_query }}{% endif %}">

            <label for="after">Date Range: </label>
            <input type="date" class="input form-field" id="after" name="after" value="{{ after_query }}">

            <label for="before">-</label>
            <input type="date" class="input form-field" id="before" name="before" value="{{ before_query }}">

            <label for="status">Status:</label>
            <select class="input form-field" id="status" name="status">
                <option value="All" {% if status_query == None %}selected{% endif %}>All</option>
                <option value="New" {% if status_query == "New" %}selected{% endif %}>New</option>
                <option value="In Progress" {% if status_query == "in_progress" %}selected{% endif %}>In Progress</option>
                <option value="Resolved" {% if status_query == "Resolved" %}selected{% endif %}>Resolved</option>
            </select>

            <button type="submit" class="button">Search</button>
            <button type="submit" class="button" name="reset" value="true">Reset Filters</button>
        </form>
    </div>
     {% if user.is_authenticated and 'admin' in user_groups %}
         {% if report_data %}
         <ul class="list-group report_list">
            {% for data in report_data %}
                <li class="list-group-item report_list">
                    <h2><a href="{% url 'orgreport:report_detail' data.report.id %}" class="link">Report # {{ data.report.id }}</a></h2>
                    <strong>
                        Organization:
                    </strong>
                    {{ data.report.organization }}
                    <h3>Associated User</h3>
                    {% if data.report.anonymous_account %}
                        <strong>The report was submitted anonymously</strong>
                    {% else %}
                        <strong>
                            Full Name: 
                        </strong>
                        {{ data.report.user.first_name }} {{ data.report.user.last_name }}
                        <strong> | Email: </strong>
                        {{ data.report.user.email }}
                    {% endif %}
                    <br>
                    <strong>
                        Status: 
                    </strong>
                    {% if data.report.status == 'in_progress' %}
                        In Progress
                    {% elif data.report.status == 'resolved' %}
                        Resolved
                    {% else %}
                        New
                    {% endif %}
                </li>
            {% endfor %}
        </ul>        
         {% else %}
             <p>No reports found.</p>
         {% endif %}
     {% else %}
         <div class="alert alert-danger" role="alert">
             You do not have permission to view this content.
         </div>
     {% endif %}
     <a href="{% url 'orgreport:home' %}" class="btn mt-3 butt">Back to Home</a>
 </div>
 {% endblock %}
 